version: '3.8'

networks:
  net_backend: ~

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './app:/app'
    networks:
      - net_backend
    depends_on:
      - mysql

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - './app:/app'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    networks:
      - net_backend
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql
    restart: always
    volumes:
      - './docker/volume/mysql/db:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: paybis
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - net_backend

  cron:
    build:
      context: .
      dockerfile: docker/cron/Dockerfile
    volumes:
      - './app:/app'
    environment:
      - ENV_VAR_NAME=env_value
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - php
      - mysql
    networks:
      - net_backend